#!/usr/bin/env php
<?php
// migrate:make command using `date` function
date_default_timezone_set('Asia/Tokyo');

require_once __DIR__ . '/../vendor/autoload.php';

$connection = [
    'driver' => 'mysql',
    'host' => '127.0.0.1',
    'database' => 'sample_db',
    'username' => 'root',
    'password' => '',
    'charset' => 'utf8',
    'collation' => 'utf8_general_ci',
    'prefix' => '',
];

$db = new \Illuminate\Database\Capsule\Manager();
$db->addConnection($connection);

$container = new \Illuminate\Container\Container();
$container['path'] = __DIR__;
$container['db'] = $db;
$container['files'] = new \Illuminate\Filesystem\Filesystem();

$console = new \Symfony\Component\Console\Application('Migrator', '0.0.1');
$console->add(new \Migrations\Console\AutoloadCommand());
$provider = new \Migrations\MigrationProvider($console, $container);
$provider->register();
exit($console->run());
